name: Build Photopea Desktop
on: [workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm run package # Або інша команда збірки, вказана в package.json
      - uses: actions/upload-artifact@v3
        with:
          name: Photopea-Windows
          path: out/ # Вкажіть правильну папку з готовим .exe
